# Generated by Django 3.1.3 on 2020-12-31 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deptartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_name', to='ticketapp.department'),
        ),
    ]
