# Generated by Django 3.1.3 on 2020-12-31 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_auto_20201231_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sect_name', to='ticketapp.section'),
        ),
    ]
