# Generated by Django 3.1.3 on 2020-12-31 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0003_auto_20201231_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.CharField(choices=[('SW', 'software'), ('HW', 'hardware')], default='SW', max_length=2)),
                ('description', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='problems',
            name='problem_type',
        ),
        migrations.AddField(
            model_name='user',
            name='pc_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='p_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='ticketapp.problemtype'),
        ),
    ]
