# Generated by Django 3.1.3 on 2020-12-31 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0004_auto_20201231_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='p_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='ticketapp.problemtype'),
        ),
    ]
