# Generated by Django 3.1.3 on 2020-12-31 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0005_auto_20201231_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deptartment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dept_name', to='ticketapp.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sect_name', to='ticketapp.section'),
        ),
    ]
