# Generated by Django 3.1.3 on 2020-12-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0007_auto_20201231_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
