# Generated by Django 3.1.3 on 2021-01-04 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0008_problems_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='date',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='problems',
            name='user_solver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='has_solution', to=settings.AUTH_USER_MODEL),
        ),
    ]
